import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@fontsource/dosis";
 import { Dosis, Inter } from "next/font/google";

 const dosis = Dosis({
   subsets: ["latin"],
   variable: "--font-dosis", // export as CSS variable
 });

 const inter = Inter({
   subsets: ["latin"],
   variable: "--font-inter",
 });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${dosis.variable} ${inter.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
